version: '2'
services:
## this file is for service that are always on and independant from  the web services 
    fs:  
        volumes:
            - /home/vipconsult/freeswitch/master/conf:/usr/local/freeswitch/conf
            - /home/vipconsult/freeswitch/master/sounds:/usr/local/freeswitch/sounds
            - /home/vipconsult/freeswitch/master/ssl:/usr/local/freeswitch/ssl
        extends:
            file: always-on-dev.yml
            service: fs
        env_file:
            - env-prod
        image: vipconsult/freeswitch:1.4
    psql_fs:
        volumes:
            - /home/vipconsult/postgresql:/var/lib/postgresql/data
        env_file:
            - env-prod
        extends:
            file: always-on-dev.yml
            service: psql_fs
    ftp:
        extends:
            file: always-on-dev.yml
            service: ftp
        volumes:
            - /home:/home
            - /home/vipconsult/proftpd/ftpd.passwd:/etc/proftpd/ftpd.passwd
        env_file:
            - env-prod
        image: vipconsult/proftpd

    logger:
        extends:
            file: always-on-dev.yml
            service: logger
        env_file:
            - env-prod


    simplehelp:
        extends:
            file: always-on-dev.yml
            service: simplehelp
        volumes:
            - /home/vipconsult/simplehelp/configuration:/home/SimpleHelp/configuration
        env_file:
            - env-prod
        build: ../docker/simplehelp/
        # entrypoint: "/bin/bash"
        # command: "-c 'ping google.com'"
