version: '2'
services:
    nginx:
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../http:/home/http
            - ../http/ngx_pagespeed_cache:/var/ngx_pagespeed_cache
        extends:
             file: common-dev.yml
             service: common

    php53:
        volumes:
            - ../http:/home/http
            # saves the sessions there so that when the container is restarted the sessions are not deleted
            - /tmp:/tmp
        extends:
            file: common-dev.yml
            service: common
    php5:
        volumes:
            - ../http:/home/http
            # saves the sessions there so that when the container is restarted the sessions are not deleted
            - /tmp:/tmp
        extends:
             file: common-dev.yml
             service: common
        environment:
            - PHP53_display_errors=on
            - PHP5_display_errors=on
    smtp:
        volumes:
            - ../exim:/var/spool/exim4
        extends:
             file: common-dev.yml
             service: common

    psql:
        volumes:
            - ../postgresql:/var/lib/postgresql/data
        extends:
             file: common-dev.yml
             service: common
    mysql:
        # so that we can connect shrough ssh
        volumes:
            - ../mysql:/var/lib/mysql
        extends:
             file: common-dev.yml
             service: common
    cron:
        extends:
             file: common-dev.yml
             service: common
    memcached:
        extends:
             file: common-dev.yml
             service: common
    fs:
        build: ../dockerfiles/fs/
        ports:
            - 444:443
            - 19000-19100:19000-19100
            - 3478:3478
            - 3479:3479
            - 5003:5003
            - 5066:5066
            - 7443:7443
        volumes:
            - ../freeswitch/fs_new_layout/:/usr/local/freeswitch/conf
            - ../freeswitch/fs_new_layout/fs_cli.conf:/etc/fs_cli.conf
            - ../freeswitch/fs_new_layout/storage:/usr/local/freeswitch/storage
        extends:
            file: common-dev.yml
            service: common
        # image: vipconsult/freeswitch:1.6
        # entrypoint: 'bash -c '
        # command: '"ping google.com"'
    # psql_fs:
    #     ports:
    #         - 5433:5432
    #     volumes:
    #         - ../postgresqlFs:/var/lib/postgresql/data
    #     extends:
    #         file: common-dev.yml
    #         service: common
